# Generated by Django 5.0.6 on 2026-06-24 19:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fieldbook', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(blank=True, help_text='Official phytosanitary registration number.', max_length=60, verbose_name='nº registro')),
                ('active_ingredient', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('HERBICIDE', 'Herbicida'), ('FUNGICIDE', 'Fungicida'), ('INSECTICIDE', 'Insecticida'), ('FERTILIZER', 'Fertilizante'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('unit', models.CharField(default='L', help_text='L, kg, units…', max_length=20)),
                ('safety_interval_days', models.PositiveIntegerField(default=0, help_text='Plazo de seguridad (pre-harvest interval).')),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('ADJUST', 'Ajuste')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('signed_quantity', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='fieldbook.treatment')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
