# Generated by Django 5.0.6 on 2026-06-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockbatch_stockmovement_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cost per unit, used for automatic cost imputation.', max_digits=12),
        ),
    ]
