# Generated by Django 5.0.6 on 2026-06-24 20:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0003_harvestrecord_price_per_kg'),
        ('fieldbook', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('LABOR', 'Mano de obra'), ('PRODUCT', 'Producto / insumo'), ('MACHINE', 'Maquinaria'), ('WATER', 'Agua / riego'), ('ELECTRICITY', 'Electricidad'), ('OTHER', 'Otro')], max_length=20)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('TREATMENT', 'Tratamiento'), ('OPERATION', 'Operación de campo')], default='MANUAL', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_entries', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_entries', to='farms.crop')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_entries', to='fieldbook.fieldoperation')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_entries', to='fieldbook.treatment')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfitabilityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost_per_ha', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
                ('crop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profitability', to='farms.crop')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='costentry',
            constraint=models.UniqueConstraint(condition=models.Q(('treatment__isnull', False)), fields=('treatment',), name='unique_cost_per_treatment'),
        ),
    ]
