# Generated by Django 5.0.6 on 2026-06-24 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('trigger', models.CharField(choices=[('STOCK', 'Stock mínimo'), ('EXPIRY', 'Caducidad de lote'), ('SAFETY', 'Plazo de seguridad'), ('COMPLIANCE', 'Cumplimiento normativo'), ('WEATHER', 'Meteorología'), ('PRODUCTION', 'Producción'), ('MAINTENANCE', 'Mantenimiento')], max_length=20)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('INFO', 'Información'), ('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
            ],
            options={
                'ordering': ['trigger', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('STOCK', 'Stock mínimo'), ('EXPIRY', 'Caducidad de lote'), ('SAFETY', 'Plazo de seguridad'), ('COMPLIANCE', 'Cumplimiento normativo'), ('WEATHER', 'Meteorología'), ('PRODUCTION', 'Producción'), ('MAINTENANCE', 'Mantenimiento')], max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Información'), ('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(db_index=True, max_length=200)),
                ('acknowledged', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.alertrule')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved', False)), fields=('cooperative', 'dedupe_key'), name='unique_open_alert_per_key'),
        ),
    ]
