# Generated by Django 5.0.6 on 2026-06-24 19:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_type', models.CharField(choices=[('AGRONOMIST', 'Agente Agrónomo'), ('ADMIN', 'Agente Administrativo'), ('COOPERATIVE', 'Agente Cooperativa'), ('SUPPORT', 'Agente de Soporte')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('purpose', models.TextField()),
                ('model', models.CharField(default='gpt-4o-mini', max_length=60)),
                ('system_prompt', models.TextField()),
                ('skills', models.JSONField(blank=True, default=list)),
                ('tools', models.JSONField(blank=True, default=list, help_text='Registered tool names.')),
                ('listens_to', models.JSONField(blank=True, default=list, help_text="Domain events, e.g. ['treatment_registered'].")),
                ('is_active', models.BooleanField(default=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
            ],
            options={
                'ordering': ['agent_type', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'Ejecutando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=12)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='agents.agent')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('system', 'system'), ('user', 'user'), ('assistant', 'assistant'), ('tool', 'tool')], max_length=12)),
                ('content', models.TextField(blank=True)),
                ('tool_name', models.CharField(blank=True, max_length=80)),
                ('tool_calls', models.JSONField(blank=True, null=True)),
                ('tool_call_id', models.CharField(blank=True, max_length=80)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.agentrun')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
