# Generated by Django 5.0.6 on 2026-06-24 19:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(choices=[('SOWING', 'Siembra'), ('FERTILIZATION', 'Abonado'), ('IRRIGATION', 'Riego'), ('TREATMENT', 'Tratamiento fitosanitario'), ('PRUNING', 'Poda'), ('HARVEST', 'Cosecha'), ('OTHER', 'Otro')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('area_ha', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='farms.crop')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('dose', models.DecimalField(decimal_places=4, max_digits=12)),
                ('dose_unit', models.CharField(default='L/ha', max_length=20)),
                ('total_quantity', models.DecimalField(decimal_places=2, help_text='Total product consumed (in product unit).', max_digits=12)),
                ('target_pest', models.CharField(blank=True, max_length=200)),
                ('weather', models.CharField(blank=True, max_length=200)),
                ('safety_interval_ok', models.BooleanField(default=True)),
                ('applicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to=settings.AUTH_USER_MODEL)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='farms.crop')),
                ('operation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='fieldbook.fieldoperation')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'abstract': False,
            },
        ),
    ]
