# Generated by Django 5.0.6 on 2026-06-24 21:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_cooperative_mfa_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('LOGIN_SUCCESS', 'Inicio de sesión correcto'), ('LOGIN_FAILED', 'Inicio de sesión fallido'), ('LOGIN_MFA_REQUIRED', 'MFA requerido'), ('MFA_ENROLLED', 'MFA registrado'), ('LOGOUT', 'Cierre de sesión')], max_length=32)),
                ('email', models.EmailField(blank=True, help_text='Captured even if user is unknown.', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tenants.cooperative')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'created_at'], name='audit_audit_event_07f862_idx'), models.Index(fields=['email'], name='audit_audit_email_7782e2_idx')],
            },
        ),
    ]
