# Generated by Django 5.0.6 on 2026-06-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Inicio de sesión correcto'), ('LOGIN_FAILED', 'Inicio de sesión fallido'), ('LOGIN_MFA_REQUIRED', 'MFA requerido'), ('MFA_ENROLLED', 'MFA registrado'), ('LOGOUT', 'Cierre de sesión'), ('USER_REGISTERED', 'Alta de usuario'), ('PASSWORD_CHANGED', 'Cambio de contraseña')], max_length=32),
        ),
    ]
