# Generated by Django 5.0.6 on 2026-06-24 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='polygon',
            field=models.JSONField(blank=True, help_text='GeoJSON-like list of [lon, lat] points delimiting the parcel.', null=True),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='e.g. 2025/2026', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
            ],
            options={
                'ordering': ['-label'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crops', to='farms.campaign'),
        ),
        migrations.CreateModel(
            name='HarvestRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quality_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Quality score/grade (e.g. % or rendimiento graso).', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='farms.crop')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('area_ha', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='area (ha)')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='farms.parcel')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crops', to='farms.sector'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(fields=('cooperative', 'label'), name='unique_campaign_per_coop'),
        ),
    ]
