# Generated by Django 5.0.6 on 2026-06-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_parcel_polygon_campaign_crop_season_harvestrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestrecord',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Sale price per kg, used to compute crop income.', max_digits=10, null=True),
        ),
    ]
