# Generated by Django 5.0.6 on 2026-06-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_harvestrecord_price_per_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color used to render the zone on the map.', max_length=9),
        ),
        migrations.AddField(
            model_name='sector',
            name='polygon',
            field=models.JSONField(blank=True, help_text='GeoJSON-like list of [lon, lat] points delimiting the zone.', null=True),
        ),
    ]
