# Generated by Django 5.0.6 on 2026-06-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_sector_color_sector_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='location/address'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='municipality',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='parcel',
            name='province',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
