# Generated by Django 5.0.6 on 2026-06-25 09:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0005_parcel_address_parcel_municipality_parcel_province'),
        ('tenants', '0004_cooperativesettings_weather_alerts_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('TODO', 'Pendiente'), ('IN_PROGRESS', 'En curso'), ('DONE', 'Completada')], default='TODO', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta')], default='MEDIUM', max_length=10)),
                ('category', models.CharField(choices=[('SOWING', 'Siembra'), ('FERTILIZATION', 'Abonado'), ('IRRIGATION', 'Riego'), ('TREATMENT', 'Tratamiento fitosanitario'), ('PRUNING', 'Poda'), ('HARVEST', 'Cosecha'), ('MAINTENANCE', 'Mantenimiento'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='farms.crop')),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='farms.parcel')),
            ],
            options={
                'ordering': ['status', 'due_date', '-priority', '-created_at'],
                'abstract': False,
            },
        ),
    ]
