# Generated by Django 5.0.6 on 2026-06-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'Pendiente'), ('IN_PROGRESS', 'En curso'), ('BLOCKED', 'Bloqueada'), ('DONE', 'Completada')], default='TODO', max_length=20),
        ),
    ]
