# Generated by Django 5.0.6 on 2026-06-25 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, help_text='Team members responsible for this task (zero, one or many).', related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Creada'), ('STATUS_CHANGED', 'Cambio de estado'), ('PRIORITY_CHANGED', 'Cambio de prioridad'), ('CATEGORY_CHANGED', 'Cambio de categoría'), ('ASSIGNED', 'Asignación'), ('UNASSIGNED', 'Desasignación'), ('DUE_DATE_CHANGED', 'Cambio de fecha límite'), ('EDITED', 'Edición'), ('COMMENT', 'Comentario')], max_length=24),
        ),
    ]
