# Generated by Django 5.0.6 on 2026-06-25 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_assigned_to_task_assignees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskactivity',
            name='mentions',
            field=models.ManyToManyField(blank=True, help_text='Team members mentioned (via @) in a comment.', related_name='task_mentions', to=settings.AUTH_USER_MODEL),
        ),
    ]
