# Generated by Django 5.0.6 on 2026-06-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='mfa_required',
            field=models.BooleanField(default=False, help_text='Require MFA for all members of this cooperative.'),
        ),
        migrations.AlterField(
            model_name='cooperativemembership',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadministrador'), ('COOP_ADMIN', 'Admin cooperativa'), ('AGRONOMIST', 'Técnico agrónomo'), ('FARMER', 'Agricultor'), ('OPERATOR', 'Operario'), ('AUDITOR', 'Auditor')], default='FARMER', max_length=20),
        ),
    ]
