# Generated by Django 5.0.6 on 2026-06-24 22:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_cooperative_mfa_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperativeSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='EUR', help_text='ISO 4217 code shown across the UI.', max_length=3)),
                ('default_operation_cost', models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Default labour cost imputed per field operation.', max_digits=10)),
                ('stock_alerts_enabled', models.BooleanField(default=True)),
                ('expiry_alerts_enabled', models.BooleanField(default=True)),
                ('safety_alerts_enabled', models.BooleanField(default=True)),
                ('expiry_alert_days', models.PositiveIntegerField(default=30, help_text='Default days-before-expiry threshold for expiry alerts.')),
                ('display_name', models.CharField(blank=True, help_text='Brand name shown in the UI. Defaults to the cooperative name.', max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('primary_color', models.CharField(default='#16a34a', help_text='Primary brand colour (hex), e.g. #16a34a.', max_length=7)),
                ('logo_emoji', models.CharField(default='🌱', max_length=8)),
                ('agents_enabled', models.BooleanField(default=True, help_text='Expose the AI agents module in the UI.')),
                ('traceability_enabled', models.BooleanField(default=True)),
                ('cooperative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.cooperative')),
            ],
            options={
                'verbose_name': 'Cooperative settings',
                'verbose_name_plural': 'Cooperative settings',
            },
        ),
    ]
