# Generated by Django 5.0.6 on 2026-06-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_cooperativesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativesettings',
            name='weather_alerts_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
