# Generated by Django 5.0.6 on 2026-06-24 19:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('USER', 'Memoria de usuario'), ('PARCEL', 'Memoria de parcela/cultivo'), ('GLOBAL', 'Memoria global del sistema')], max_length=10)),
                ('key', models.CharField(blank=True, help_text='Optional dedup key.', max_length=120)),
                ('content', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('importance', models.PositiveSmallIntegerField(default=1)),
                ('source', models.CharField(default='system', help_text="Who wrote it: 'system', 'agent:<name>', 'user'.", max_length=60)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cooperative')),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='farms.crop')),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='farms.parcel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-importance', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['cooperative', 'scope'], name='memory_memo_coopera_75c358_idx'), models.Index(fields=['cooperative', 'scope', 'key'], name='memory_memo_coopera_d90c19_idx')],
            },
        ),
    ]
